cp: cp.o
	gcc -Wall -g cp.o -o cp
cp.o: cp.c
	gcc -c cp.c -o cp.o
ls: ls.o
	gcc -Wall -g ls.o -o ls
ls.o: ls.c
	gcc -c ls.c -o ls.o
cmp: cmp.o
	gcc -Wall -g cmp.o -o cmp
cmp.o: cmp.c
	gcc -c cmp.c -o cmp.o
clean:
	rm -rf *.o
